In [20]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from collections import Counter

In [36]:
df = pd.read_csv('out/llm_result.csv')
df.head()

,категория_товара,бренд,категория_вопроса,запрос,текст_ответа,ссылки_в_тексте,сайты_в_тексте,ссылки_из_блока_источников,сайты_из_блока_источников,q_brand_direct,...,a_pg_portfolio_count,a_comp_count,a_main_competitor,a_comp_is_winner,a_sentiment,a_has_tech,a_has_price,a_buy_cta,a_comparison_type,a_source_trust
0,гигиена,Always,брендовые,Always Platinum vs Always Ultra: основные отличия,Always Platinum и Always Ultra — это линейки г...,https://graph.org,graph.org,https://zdravcity.ru/p_olvejz-prokladki-zhen-g...,zdravcity.ru\napteka.ru\notvet.mail.ru\npodryg...,1,...,2,0,none,0,1,1,0,1,внутри_pg,6
1,гигиена,Always,брендовые,Где заказать Always в большой упаковке (Big Pa...,Прокладки Always в большой упаковке (Big Pack)...,https://WildBerries.ru\nhttps://OZON.ru\nhttps...,wildberries.ru\nozon.ru\nmarket.yandex.ru,https://www.wildberries.ru/catalog/krasota/sre...,wildberries.ru\nozon.ru\neapteka.ru\nozerki.ru...,1,...,1,0,none,0,1,0,1,0,нет_сравнения,1
2,гигиена,Always,брендовые,Где найти Always Ultra Normal по акции?,Прокладки Always Ultra Normal можно найти по а...,https://spb.rigla.ru\nhttps://lenta.com\nhttps...,spb.rigla.ru\nlenta.com\nozon.ru\nozerki.ru\ns...,https://apteka.ru/sanktpeterburg/product/alway...,apteka.ru\nlenta.com\npodrygka.ru\neapteka.ru\...,1,...,1,0,none,0,0,0,1,1,нет_сравнения,6
3,гигиена,Always,брендовые,Есть ли у Always экологичные линейки прокладок?,В доступных источниках не удалось найти информ...,https://market.yandex.ru\nhttps://r-ulybka.ru\...,market.yandex.ru\nr-ulybka.ru\nwildberries.ru\...,https://market.yandex.ru/card/nezametnaya-zash...,market.yandex.ru\nwildberries.ru\nnovex.ru\nal...,1,...,1,3,Organyc,1,0,1,0,0,с_конкурентом,6
4,гигиена,Always,брендовые,Какие размеры есть в линейке Always Ultra?,В линейке прокладок Always Ultra представлены ...,NaN,NaN,https://www.sima-land.ru/1163519/prokladki-alw...,sima-land.ru\nporyadok.ru\nparfum-lider.ru,1,...,1,0,none,0,0,1,0,0,нет_сравнения,3

In [46]:
df.describe()

,q_brand_direct,q_comp_direct,a_pg_rank,a_is_winner,a_pg_portfolio_count,a_comp_count,a_comp_is_winner,a_sentiment,a_has_tech,a_has_price,a_buy_cta,a_source_trust
count,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000
mean,0.441667,0.004167,0.770833,0.037500,0.862500,1.483333,0.045833,0.329167,0.475000,0.158333,0.108333,4.104167
std,0.497623,0.064550,1.345060,0.190381,1.161557,2.469846,0.209561,0.479696,0.500418,0.365816,0.311450,1.884084
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
50%,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
75%,1.000000,0.000000,1.000000,0.000000,1.000000,3.000000,0.000000,1.000000,1.000000,0.000000,0.000000,6.000000
max,1.000000,1.000000,14.000000,1.000000,7.000000,12.000000,1.000000,1.000000,1.000000,1.000000,1.000000,6.000000

Index(['категория_товара', 'бренд', 'категория_вопроса', 'запрос',
       'текст_ответа', 'ссылки_в_тексте', 'сайты_в_тексте',
       'ссылки_из_блока_источников', 'сайты_из_блока_источников',
       'q_brand_direct', 'q_comp_direct', 'a_pg_rank', 'a_is_winner',
       'a_pg_portfolio_count', 'a_comp_count', 'a_main_competitor',
       'a_comp_is_winner', 'a_sentiment', 'a_has_tech', 'a_has_price',
       'a_buy_cta', 'a_comparison_type', 'a_source_trust'],
      dtype='str')